# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES :=  \
    vendor/htc/shooter/proprietary/camera.default.so:obj/lib/hw/camera.default.so \
    vendor/htc/shooter/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so

# All the blobs necessary for vivow
PRODUCT_COPY_FILES += \
vendor/htc/shooter/proprietary/3D_calibration:/system/bin/3D_calibration \
vendor/htc/shooter/proprietary/3D_calibration_main:/system/bin/3D_calibration_main \
vendor/htc/shooter/proprietary/charging:/system/bin/charging \
vendor/htc/shooter/proprietary/htcbatt:/system/bin/htcbatt \
vendor/htc/shooter/proprietary/logcat2:/system/bin/logcat2 \
vendor/htc/shooter/proprietary/load-modem.sh:/system/bin/load-modem.sh \
vendor/htc/shooter/proprietary/mpdecision:/system/bin/mpdecision \
vendor/htc/shooter/proprietary/netmgrd:/system/bin/netmgrd \
vendor/htc/shooter/proprietary/qmuxd:/system/bin/qmuxd \
vendor/htc/shooter/proprietary/rmt_storage:/system/bin/rmt_storage \
vendor/htc/shooter/proprietary/sound8x60:/system/bin/sound8x60 \
vendor/htc/shooter/proprietary/thermald:/system/bin/thermald \
vendor/htc/shooter/proprietary/libchromatix_imx074_default_video.so:/system/lib/libchromatix_imx074_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_imx074_preview.so:/system/lib/libchromatix_imx074_preview.so \
vendor/htc/shooter/proprietary/libchromatix_imx105_default_video.so:/system/lib/libchromatix_imx105_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_imx105_preview.so:/system/lib/libchromatix_imx105_preview.so \
vendor/htc/shooter/proprietary/libchromatix_mt9e013_ar.so:/system/lib/libchromatix_mt9e013_ar.so \
vendor/htc/shooter/proprietary/libchromatix_mt9e013_default_video.so:/system/lib/libchromatix_mt9e013_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_mt9e013_preview.so:/system/lib/libchromatix_mt9e013_preview.so \
vendor/htc/shooter/proprietary/libchromatix_mt9p012_ar.so:/system/lib/libchromatix_mt9p012_ar.so \
vendor/htc/shooter/proprietary/libchromatix_mt9p012_default_video.so:/system/lib/libchromatix_mt9p012_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_mt9p012_km_default_video.so:/system/lib/libchromatix_mt9p012_km_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_mt9p012_km_preview.so:/system/lib/libchromatix_mt9p012_km_preview.so/ \
vendor/htc/shooter/proprietary/libchromatix_mt9p012_preview.so:/system/lib/libchromatix_mt9p012_preview.so \
vendor/htc/shooter/proprietary/libchromatix_mt9t013_default_video.so:/system/lib/libchromatix_mt9t013_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_mt9t013_preview.so:/system/lib/libchromatix_mt9t013_preview.so \
vendor/htc/shooter/proprietary/libchromatix_ov8810_default_video.so:/system/lib/libchromatix_ov8810_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_ov8810_preview.so:/system/lib/libchromatix_ov8810_preview.so \
vendor/htc/shooter/proprietary/libchromatix_ov9726_preview.so:/system/lib/libchromatix_ov9726_preview.so \
vendor/htc/shooter/proprietary/libchromatix_ov9726_video.so:/system/lib/libchromatix_ov9726_video.so \
vendor/htc/shooter/proprietary/libchromatix_qs_s5k4e1_preview.so:/system/lib/libchromatix_qs_s5k4e1_preview.so \
vendor/htc/shooter/proprietary/libchromatix_qs_s5k4e1_video.so:/system/lib/libchromatix_qs_s5k4e1_video.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3e2fx_default_video.so:/system/lib/libchromatix_s5k3e2fx_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3e2fx_preview.so:/system/lib/libchromatix_s5k3e2fx_preview.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3h1gx_default_video.so:/system/lib/libchromatix_s5k3h1gx_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3h1gx_preview.so:/system/lib/libchromatix_s5k3h1gx_preview.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
vendor/htc/shooter/proprietary/libchromatix_s5k4e1gx_default_video.so:/system/lib/libchromatix_s5k4e1gx_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_s5k4e1gx_preview.so:/system/lib/libchromatix_s5k4e1gx_preview.so \
vendor/htc/shooter/proprietary/libchromatix_sn12m0pz_default_video.so:/system/lib/libchromatix_sn12m0pz_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_sn12m0pz_preview.so:/system/lib/libchromatix_sn12m0pz_preview.so \
vendor/htc/shooter/proprietary/libchromatix_vb6801_default_video.so:/system/lib/libchromatix_vb6801_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_vb6801_preview.so:/system/lib/libchromatix_vb6801_preview.so \
vendor/htc/shooter/proprietary/libchromatix_vx6953_default_video.so:/system/lib/libchromatix_vx6953_default_video.so \
vendor/htc/shooter/proprietary/libchromatix_vx6953_preview.so:/system/lib/libchromatix_vx6953_preview.so \
vendor/htc/shooter/proprietary/drmserver:/system/bin/drmserver \
vendor/htc/shooter/proprietary/DxDrmServerIpc:/system/bin/DxDrmServerIpc \
vendor/htc/shooter/proprietary/DxDrmConfig_Server.txt:/system/etc/DxDrmConfig_Server.txt \
vendor/htc/shooter/proprietary/com.google.widevine.software.drm.xml:/system/etc/permissions/com.google.widevine.software.drm.xml \
vendor/htc/shooter/proprietary/com.google.widevine.software.drm.jar:/system/framework/com.google.widevine.software.drm.jar \
vendor/htc/shooter/proprietary/libdivxdrmdecrypt.so:/system/lib/libdivxdrmdecrypt.so \
vendor/htc/shooter/proprietary/libdrm1.so:/system/lib/libdrm1.so \
vendor/htc/shooter/proprietary/libdrm1_jni.so:/system/lib/libdrm1_jni.so \
vendor/htc/shooter/proprietary/libdrmframework.so:/system/lib/libdrmframework.so \
vendor/htc/shooter/proprietary/libdrmframework_jni.so:/system/lib/libdrmframework_jni.so \
vendor/htc/shooter/proprietary/libDxDrmCAPI.so:/system/lib/libDxDrmCAPI.so \
vendor/htc/shooter/proprietary/libDxDrmJava.so:/system/lib/libDxDrmJava.so \
vendor/htc/shooter/proprietary/liboma-drm1-fs.so:/system/lib/liboma-drm1-fs.so \
vendor/htc/shooter/proprietary/libwvdrm_L3.so:/system/lib/libwvdrm_L3.so \
vendor/htc/shooter/proprietary/libdrmwvmplugin.so:/system/lib/drm/libdrmwvmplugin.so \
vendor/htc/shooter/proprietary/libhtcomaplugin.so:/system/lib/drm/libhtcomaplugin.so \
vendor/htc/shooter/proprietary/dmagent:/system/bin/dmagent \
vendor/htc/shooter/proprietary/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \
vendor/htc/shooter/proprietary/sequansd:/system/bin/sequansd \
vendor/htc/shooter/proprietary/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \
vendor/htc/shooter/proprietary/setWiMAXPropDaemond.mod.so:/system/bin/setWiMAXPropDaemond.mod.so \
vendor/htc/shooter/proprietary/wimaxAddRoute:/system/bin/wimaxAddRoute \
vendor/htc/shooter/proprietary/wimax_baud_hack.so:/system/bin/wimax_baud_hack.so \
vendor/htc/shooter/proprietary/wimaxConfigInterface:/system/bin/wimaxConfigInterface \
vendor/htc/shooter/proprietary/wimaxDaemon:/system/bin/wimaxDaemon \
vendor/htc/shooter/proprietary/wimaxDhcpRelease:/system/bin/wimaxDhcpRelease \
vendor/htc/shooter/proprietary/wimaxDhcpRenew:/system/bin/wimaxDhcpRenew \
vendor/htc/shooter/proprietary/wimaxDumpKmsg:/system/bin/wimaxDumpKmsg \
vendor/htc/shooter/proprietary/wimaxDumpLastKmsg:/system/bin/wimaxDumpLastKmsg \
vendor/htc/shooter/proprietary/wimaxDumpLogcat:/system/bin/wimaxDumpLogcat \
vendor/htc/shooter/proprietary/wimaxFactoryReset:/system/bin/wimaxFactoryReset \
vendor/htc/shooter/proprietary/wimax_mtd:/system/bin/wimax_mtd \
vendor/htc/shooter/proprietary/wimaxDhcp.conf:/system/etc/wimax/dhcp/wimaxDhcp.conf \
vendor/htc/shooter/proprietary/DefaultTree.xml:/system/etc/wimax/sequansd/DefaultTree.xml \
vendor/htc/shooter/proprietary/sequansd_app.xml:/system/etc/wimax/sequansd/sequansd_app.xml \
vendor/htc/shooter/proprietary/libcrypto.so:/system/lib/libcrypto.so \
vendor/htc/shooter/proprietary/libdmtree.so:/system/lib/libdmtree.so \
vendor/htc/shooter/proprietary/libhtcdm.so:/system/lib/libhtcdm.so \
vendor/htc/shooter/proprietary/wimax.jar:/system/framework/wimax.jar \
vendor/htc/shooter/proprietary/camera.default.so:/system/lib/hw/camera.default.so \
vendor/htc/shooter/proprietary/sensors.shooter.so:/system/lib/hw/sensors.shooter.so \
vendor/htc/shooter/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
vendor/htc/shooter/proprietary/libaudcal.so:/system/lib/libaudcal.so \
vendor/htc/shooter/proprietary/libacdbmapper.so:/system/lib/libacdbmapper.so \
vendor/htc/shooter/proprietary/libC2D2.so:/system/lib/libC2D2.so \
vendor/htc/shooter/proprietary/libcamerapp.so:/system/lib/libcamerapp.so \
vendor/htc/shooter/proprietary/libcameraSP.so:/system/lib/libcameraSP.so \
vendor/htc/shooter/proprietary/libcameraface.so:/system/lib/libcameraface.so \
vendor/htc/shooter/proprietary/libdll.so:/system/lib/libdll.so \
vendor/htc/shooter/proprietary/libdiag.so:/system/lib/libdiag.so \
vendor/htc/shooter/proprietary/libidl.so:/system/lib/libidl.so \
vendor/htc/shooter/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
vendor/htc/shooter/proprietary/libdsutils.so:/system/lib/libdsutils.so \
vendor/htc/shooter/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
vendor/htc/shooter/proprietary/libgemini.so:/system/lib/libgemini.so \
vendor/htc/shooter/proprietary/libgemini2.so:/system/lib/libgemini2.so \
vendor/htc/shooter/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
vendor/htc/shooter/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
vendor/htc/shooter/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
vendor/htc/shooter/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
vendor/htc/shooter/proprietary/libgsl.so:/system/lib/libgsl.so \
vendor/htc/shooter/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
vendor/htc/shooter/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
vendor/htc/shooter/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
vendor/htc/shooter/proprietary/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
vendor/htc/shooter/proprietary/libmmipl.so:/system/lib/libmmipl.so \
vendor/htc/shooter/proprietary/libmmmpo.so:/system/lib/libmmmpo.so \
vendor/htc/shooter/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
vendor/htc/shooter/proprietary/libmmjps.so:/system/lib/libmmjps.so \
vendor/htc/shooter/proprietary/libmmjpeg2.so:/system/lib/libmmjpeg2.so \
vendor/htc/shooter/proprietary/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \
vendor/htc/shooter/proprietary/libmm-omxcore.so:/system/lib/libmm-omxcore.so \
vendor/htc/shooter/proprietary/libmpl.so:/system/lib/libmpl.so \
vendor/htc/shooter/proprietary/libmllite.so:/system/lib/libmllite.so \
vendor/htc/shooter/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \
vendor/htc/shooter/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
vendor/htc/shooter/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
vendor/htc/shooter/proprietary/libOlaEngine.so:/system/lib/libOlaEngine.so \
vendor/htc/shooter/proprietary/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \
vendor/htc/shooter/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
vendor/htc/shooter/proprietary/libposteffect.so:/system/lib/libposteffect.so \
vendor/htc/shooter/proprietary/libqc-opt.so:/system/lib/libqc-opt.so \
vendor/htc/shooter/proprietary/libqmi.so:/system/lib/libqmi.so \
vendor/htc/shooter/proprietary/libqdp.so:/system/lib/libqdp.so \
vendor/htc/shooter/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \
vendor/htc/shooter/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
vendor/htc/shooter/proprietary/libv8.so:/system/lib/libv8.so \

